### ISSUE TITLE
Pagecontrol.ActivePage wrapper function causes AV error

### ISSUE THREAD

**Issue by Andyk1234** [pyscripter/python4delphi#447]
Noticed problem in Demo31 project as the "Go to Page 3" button produces an AV error.

Problem appears in WrapVclComCtrls unit

function TPyDelphiPageControl.Get_ActivePage(AContext: Pointer): PPyObject;
begin
  Result := Wrap(DelphiObject.ActivePage);
end;

DelphiObject has a nil value;

If fixed it by adding line

Adjust(@Self); to the start of the function.

There are several functions in the unit that don't setup DelphiObject before calls to Wrap, I suspect they will all produce AV errors.

**Comment by pyscripter** [comment]
Clearly you are not using the latest version of this repo.   This was fixed almost a year ago in https://github.com/pyscripter/python4delphi/commit/824cf1e0c1857734fd3ae971d93f318ee8f2a1d6.

**Comment by Andyk1234** [comment]
I downloaded the repo 3 days ago.

**Comment by pyscripter** [comment]
From which repo?  Here the issue is fixed.  Check for yourself.

**Comment by Andyk1234** [comment]
I am not sure what you mean by "which Repo",

I hit the <code> tag at the top left of this page then select the Green code button to the top right, then select "Download Zip"

**Comment by pyscripter** [comment]
Repo stands for repository.   Did you download your zip from https://github.com/pyscripter/python4delphi or say the Embarcadero fork?

**Comment by Andyk1234** [comment]
I downloaded from these pages, I don't see any other forks.

I have downloaded it again, I can see the fixes now, odd.

Although demo 11 still doesn't work.

**Comment by pyscripter** [comment]
It was working on 32 bits.
It is now fixed for 64 bits.  Please download again.

**Comment by Andyk1234** [comment]
Yep, works now.

Thank you.
